<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <OverrideHtmlAssetPlaceholders>true</OverrideHtmlAssetPlaceholders>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CsvHelper" Version="33.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.0.10" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\data\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\..\..\Recipies\Recipies\wwwroot\data\recipies_data.csv" Link="wwwroot\data\recipies_data.csv" />
  </ItemGroup>

</Project>
